version: "3.9"

services:
  db:
    image: postgres:15
    container_name: survey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: survey
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: survey_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/survey
      GEOIP_DB_PATH: geoip/GeoLite2-City.mmdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./geoip:/app/geoip

volumes:
  postgres_data: